# Generated by Django 5.0.5 on 2024-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_is_approved_store_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/'),
        ),
    ]
