# Generated by Django 5.0.5 on 2024-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_store_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permission',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store_request',
            field=models.BooleanField(default=False),
        ),
    ]
