# Generated by Django 5.0.5 on 2024-05-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, choices=[('Farm', 'Farm'), ('Manufacturing', 'Manufacturing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='phone',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='store_address',
            field=models.CharField(default='01234567890', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='store_name',
            field=models.CharField(default='1234567890', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='store_type',
            field=models.CharField(choices=[('Farm', 'Farm'), ('Manufacturing', 'Manufacturing')], default='1234567890', max_length=100),
            preserve_default=False,
        ),
    ]
