# Generated by Django 5.0.5 on 2024-05-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_quantity_store_address_store_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
