# Generated by Django 5.0.5 on 2024-05-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_product_quantity_alter_storerequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='phone',
            field=models.CharField(default='1234567890', max_length=20),
        ),
    ]
