# Generated by Django 5.0.5 on 2024-05-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_quantity_alter_storerequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
