# Generated by Django 5.0.5 on 2024-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_store_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
