# Generated by Django 5.0.5 on 2024-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_order_address_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cvc',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
