# Generated by Django 5.0.5 on 2024-06-18 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_storerequest_created_at_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
